### ISSUE TITLE
about the test data

### ISSUE THREAD

**Issue by jiejiangd** [AlexTS1980/COVID-CT-Mask-Net#1]
I would like to ask if the data name of the test set will be announced

**Comment by AlexTS1980** [comment]
> I would like to ask if the data name of the test set will be announced

I took the test/validation/train splits from COVIDx-CT (https://github.com/haydengunraj/COVIDNet-CT/blob/master/docs/dataset.md)

**Comment by jiejiangd** [comment]
I‘d like to ask is this data set the same as kaggle？(https://www.kaggle.com/hgunraj/covidxct)

**Comment by AlexTS1980** [comment]
> I‘d like to ask is this data set the same as kaggle？(https://www.kaggle.com/hgunraj/covidxct)

yep, 21191 images. I didn't know they put it on kaggle. Might upload my solution as well

**Comment by jiejiangd** [comment]
OK，thanks!

**Comment by jiejiangd** [comment]
As far as I know, the data set is from an article of Cell, but the number of slices described in the article is about 600,000, while the data you used is about 100,000. Why is that? And I don't think there are 600 million pieces of data available for download

**Comment by AlexTS1980** [comment]
No the data is from CNCB-NCOV website, the link is in the project. There are total of 104K images labelled at image level and 750 images with masks.

**Comment by jiejiangd** [comment]
I don't quite understand is https://www.cell.com/cell/fulltext/S0092-8674 (20), 30551-1?RSS = Yes, which cites the dataset recorded in http://ncov-ai.big.ac.cn/download?lang=en, but the article mentions 400,000 images for classification, while CNCB-ncov seems to have only 100,000 images.
